### ISSUE TITLE
Bulk Get

### ISSUE THREAD

**Issue by qpfiffer** [infoforcefeed/OlegDB#148]
Needs to happen. Round-tripping to get a bunch of keys is terrible.

**Comment by Hamcha** [comment]
I can do it if you don't want to bother with go.

**Comment by qpfiffer** [comment]
@Hamcha Doesn't matter to me, I'll probably knock it out by this weekend. It'll be a good way to test larger transactions.

**Comment by qpfiffer** [comment]
Spitablling:

`POST`ing newline delimited keys to the `/<database>/_bulk_get` endpoint should result in a series of alternating `size_t` (unsigned 32-bit integer) and `unsigned char *` streams. The first `size_t` is the size of the stream following.

The rationale for the return type is that I want to preserve the whole keyset. I figure newline delimited keys in the `POST` data is fine because why would you put newlines in your keys? I'll think on it some more or change it if I find something dumb later.

**Comment by Hamcha** [comment]
I agree, if you put \ns in your keys the front end would have tons of other issues anyway. Sadly, size_t is architecture-dependent, we need to use a fixed size.. How about int 64 (since x64 is the main target and you'd have to send what Google has in its data centers several times to overflow it)

-----Original Message-----

**Comment by qpfiffer** [comment]
@Hamcha Definitely, I was thinking a `uint64_t` would do just fine.

**Comment by qpfiffer** [comment]
This is done until someone tries to use it for binary data.
